name: 'Banco Web - CI'
#gatilhos/ triggers
on:
  workflow_dispatch:

jobs:
  cypress-tests: 
    runs-on: ubuntu-latest

    env: 
      API_BASE_URL: 'http://localhost:3000'
      PORT: 4000

    steps:
     - name: Checkout do repositorio
       uses: actions/checkout@v4

     - name: Instalar as dependencias
       run: npm install

     - name: Iniciar o servidor de mocks
       run: npm run mock-server
       
     - name: Iniciar o servidor da Aplicacao
       run: npm run server       

     - name: Executar os testes
       run: npx cypress run    
